name: CI

on:
  workflow_dispatch:

jobs:
  run-default-case:
    name: Run default case
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: none
      contents: write
      deployments: none
      id-token: none
      issues: none
      discussions: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib
      - name: Build and run
        run: |
          bash docs/source/example/data/exec.sh
      - name: Push artifact
        run: |
          git config --local user.email "36466440+NaokiHori@users.noreply.github.com"
          git config --local user.name "NaokiHori"
          git switch -c artifact
          git add artifacts
          git commit -m "Update image" -a || true
          git push -f origin artifact
